### ISSUE TITLE
html-webpack-plugin throw error when using along with uglify-es-webpack-plugin 

### ISSUE THREAD

**Issue by hossein-nasr** [noBlubb/uglify-es-webpack-plugin#10]
When I use this plugin alongside the `html-webpack-plugin`, html-wbepack-plugin throw an error saying that 

    [ '  Error: The loader "/.../node_modules/html-webpack-plugin/lib/loader.js!/myapp/app/index.ejs" didn\'t return html.\n' ]

this is my `html-webpack-plugin` configuration :

     new HtmlWebpackPlugin({
      template: 'app/index.ejs',
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeRedundantAttributes: true,
        useShortDoctype: true,
        removeEmptyAttributes: true,
        removeStyleLinkTypeAttributes: true,
        keepClosingSlash: true,
        minifyJS: true,
        minifyCSS: true,
        minifyURLs: true,
      },
      inject: true,
      output: {
        filename: 'index.html'
      }
    }),

and i use `html-loader` like this:
      {
        test: /\.html$/,
        loader: 'html-loader',
      },

**Comment by Phyks** [comment]
Same error here with `ExtractTextPlugin`. You need [this PR](https://github.com/noBlubb/uglify-es-webpack-plugin/pull/8/commits/4dc6fd0d7bf226b0bb6fb10425ddc0321705c1c0) which should have been merged and published on NPM but is not apparently.

For some reason, it seems the PR [got merged](https://github.com/noBlubb/uglify-es-webpack-plugin/commits/master) on June 26th, but then the code disappeard in the release and went back in the latest "merge" commit, which is after NPM publication.

@noBlubb Could you make a new release on NPM to fix this please? Thanks!

**Comment by noBlubb** [comment]
Sorry about that, I had my HEAD detached :/

I just published a new version (0.10.0). Sorry for the bump, but this should make sure that the version is above the lastest release 0.4.3 of webpack-contrib when I forked it, but below their current release 1.0.0-beta. I also tagged this release so it's available on github aswell. Everything has been merged and should work well enough for the moment.

I did add a deprecation notice while doing this:
**Please** do not use this package after https://github.com/webpack-contrib/uglifyjs-webpack-plugin is out of beta (actually their beta will be more stable than this package, as they do have tests in place.)

**Comment by Phyks** [comment]
Awesome, thanks!

**Comment by hossein-nasr** [comment]
It perfectly worked! thanks a lot.
