### ISSUE TITLE
Errors for non-JS files

### ISSUE THREAD

**Issue by milesj** [noBlubb/uglify-es-webpack-plugin#7]
Received this while trying to use the plugin.

ERROR in UglifyEsPlugin - styles.998b649e7fa3c5cf1e5c.css
{"message":"Unexpected character '@'","filename":"styles.998b649e7fa3c5cf1e5c.css","line":1,"col":0,"pos":0}

Should probably filter out non-JS files.

**Comment by noBlubb** [comment]
https://github.com/noBlubb/uglify-es-webpack-plugin/pull/8 by @cburschka will most likely fix this issue. Please notice that I am looking forward to migrate this plugin back into the webpack community and will therefore not spend too much time on fixing issues while this is ongoing.
